site_name: Inteligentne Podlewanie Roślin

theme:
  name: material 
  # https://icon-icons.com/icon/plant-nature-leaves-leaf-dirt-earth/141982
  favicon: assets/icon.png
  logo: assets/icon.png

extra_css:
  - assets/stylesheets/images.css

nav:
  - Wstęp: index.md
  - Harmonogram: harmonogram.md
  - Architektura: architektura.md
  - Integracja Smart Home: smarthome.md
  - Elektronika: elektronika.md
