site_name: My Docs

extra_css:
  - assets/stylesheets/images.css

nav:
  - Wstęp: index.md
  - Harmonogram: harmonogram.md
  - Architektura: architektura.md
  - Elektronika: elektronika.md

extra:
  favicon: docs/assets//plant.png
