site_name: Inteligentne Podlewanie Roślin

theme:
  name: material
  favicon: assets/favicon.ico

extra_css:
  - assets/stylesheets/images.css

nav:
  - Wstęp: index.md
  - Harmonogram: harmonogram.md
  - Architektura: architektura.md
  - Elektronika: elektronika.md
